add: config type option

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,6 +6,15 @@ env:
 on:
   workflow_dispatch:
     inputs:
+      config_type:
+        description: 'Choose a config type'
+        required: true
+        type: choice
+        default: 'production'
+        options:
+          - production
+          - peer-variant
+          - test
       config_file:
         description: 'Path to a specific config JSON file (optional). Leave blank to use all configs.'
         required: false
@@ -30,20 +39,20 @@ jobs:
 
           if [ -n "$CONFIG_FILE" ]; then
             # User provided config file, check if exists
-            if [ -f "./.github/configs/$CONFIG_FILE" ]; then
-              echo "Using specified config file: ./.github/configs/$CONFIG_FILE"
+            if [ -f "./.github/configs/${{ github.event.inputs.config_type }}/$CONFIG_FILE" ]; then
+              echo "Using specified config file: ./.github/configs/${{ github.event.inputs.config_type }}/$CONFIG_FILE"
               echo "repos<<EOF" >> $GITHUB_OUTPUT
-              jq -s '[.[][]]' "./.github/configs/$CONFIG_FILE" >> $GITHUB_OUTPUT
+              jq -s '[.[][]]' "./.github/configs/${{ github.event.inputs.config_type }}/$CONFIG_FILE" >> $GITHUB_OUTPUT
               echo "EOF" >> $GITHUB_OUTPUT
             else
-              echo "ERROR: Specified config file './.github/configs/$CONFIG_FILE' does not exist!" >&2
+              echo "ERROR: Specified config file './.github/configs/${{ github.event.inputs.config_type }}/$CONFIG_FILE' does not exist!" >&2
               exit 1
             fi
           else
             # No file specified, use all files
-            echo "No config_file input provided. Using all .github/configs/*.json files."
+            echo "No config_file input provided. Using all .github/configs/${{ github.event.inputs.config_type }}/*.json files."
             echo "repos<<EOF" >> $GITHUB_OUTPUT
-            jq -s '[.[][]]' .github/configs/*.json >> $GITHUB_OUTPUT
+            jq -s '[.[][]]' .github/configs/${{ github.event.inputs.config_type }}/*.json >> $GITHUB_OUTPUT
             echo "EOF" >> $GITHUB_OUTPUT
           fi
       - name: "Set builddate"
